### ISSUE TITLE
Add test for credentials in validate function

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-briteverify#15]
This integration should skip with the reason "Missing credentials, contact ActiveProspect support" reason when credential environment variables are missing.

**Comment by cgrayson** [comment]
As we discussed yesterday, let's have this be the first to get new metadata about environment variables, too. As I recall, we want a function, called `envVariables()`, that's similar to `requestVariables()`, that returns an array of strings, which are the environment variable names (e.g., `BRITEVERIFY_API_KEY`, from [this line](https://github.com/activeprospect/leadconduit-integration-briteverify/blob/master/src/email.coffee#L9)).

**Comment by cgrayson** [comment]
Revising: let's make this new array a simple property, rather than a function that returns one.
